apiVersion: v1
kind: Service
metadata:
  name: {{ template "baas-operator.fullname" $ }}-metrics
  labels:
    app: {{ template "baas-operator.name" $ }}
    chart: {{ template "baas-operator.chart" $ }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: prometheus
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ template "baas-operator.name" $ }}
    release: {{ .Release.Name }}
  type: ClusterIP

