---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rabbitmq.fullname" . }}-creds
  labels:
    app: {{ template "rabbitmq.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  rabbitmq-user: {{ .Values.rabbitmq.user | b64enc | quote }}
  {{ if .Values.rabbitmq.password }}
  rabbitmq-password: {{ .Values.rabbitmq.password | b64enc | quote }}
  {{ else }}
  rabbitmq-password: {{ randAscii 24 | nospace | b64enc | quote }}
  {{ end }}
  rabbitmq-vhost: {{ .Values.rabbitmq.vhost | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "rabbitmq.fullname" . }}-config
  labels:
    app: {{ template "rabbitmq.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.rabbitmq.erlangCookie }}
  rabbitmq-erlang-cookie: {{ .Values.rabbitmq.erlangCookie | b64enc | quote }}
  {{ else }}
  rabbitmq-erlang-cookie: {{ randAlphaNum 32 | nospace | b64enc | quote }}
  {{ end }}
