apiVersion: v1
kind: Secret
metadata:
  name: {{ template "keycloak.fullname" . }}-http
  labels:
    app: {{ template "keycloak.name" . }}
    chart: {{ template "keycloak.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
{{- if .Release.IsInstall }}
{{- if .Values.keycloak.password }}
  password: {{ .Values.keycloak.password | b64enc | quote }}
{{- else }}
  password: {{ randAlphaNum 16 | b64enc | quote }}
{{- end }}
{{- end }}
